export const Blog = [
  {
    id: 19,
    cat: "php",
    thumb: "https://source.unsplash.com/750x600/?food,starters",
    title: "How Php Works?",
    content:
      " hey The PHP software works with the The PHP software works with the  The PHP software The PHP software works with the The PHP software works with the  The PHP software works PHP software works with the  The PHP software works  with the  The PHP software works with the The PHP software works with the The PHP software works with the  The PHP software The PHP software works with the The PHP software works with the  The PHP software works PHP software works with the  The PHP software works  with the  The PHP software works w ",
    like: 55,
    comments: 22,
    author: "Parth Maru",
    date: "2020-11-15",
    share: 15,
  },
  {
    id: 0,
    cat: "php",
    thumb: "https://source.unsplash.com/750x600/?food,starters",
    title: "How Php Works?",
    content:
      " hey The PHP software works with the The PHP software works with the  The PHP software The PHP software works with the The PHP software works with the  The PHP software works PHP software works with the  The PHP software works  with the  The PHP software works with the The PHP software works with the The PHP software works with the  The PHP software The PHP software works with the The PHP software works with the  The PHP software works PHP software works with the  The PHP software works  with the  The PHP software works w ",
    like: 55,
    comments: 22,
    author: "vishw kadu",
    date: "2020-11-15",
    share: 15,
  },
  {
    id: 1,
    cat: "php",
    thumb: "https://source.unsplash.com/750x600/?food,starters",
    title: "How Php Works?",
    content:
      "The PHP software works with the The PHP software works with the  The PHP software works with the  The PHP software works with the ",
    like: 55,
    comments: 22,
    author: "Shubh Jani",
    date: "2020-11-15",
    share: 15,
  },
  {
    id: 2,
    cat: "php",
    thumb: "https://source.unsplash.com/750x600/?food,starters",
    title: "How Php Works?",
    content:
      "The PHP software works with the The PHP software works with the  The PHP software works with the  The PHP software works with the ",
    like: 55,
    comments: 22,
    author: "Parth Maru",
    date: "2020-11-15",
    share: 15,
  },
  {
    id: 3,
    cat: "php",
    thumb: "https://source.unsplash.com/750x600/?food,starters",
    title: "How Php Works?",
    content:
      "The PHP software works with the The PHP software works with the  The PHP software works with the  The PHP software works with the ",
    like: 55,
    comments: 22,
    author: "Parth Maru",
    date: "2020-11-15",
    share: 15,
  },
  {
    id: 4,
    cat: "php",
    thumb: "https://source.unsplash.com/750x600/?food,starters",
    title: "How Php Works?",
    content:
      "The PHP software works with the The PHP software works with the  The PHP software works with the  The PHP software works with the ",
    like: 55,
    comments: 22,
    author: "vishw kadu",
    date: "2020-11-15",
    share: 15,
  },
  {
    id: 5,
    cat: "php",
    thumb: "https://source.unsplash.com/750x600/?food,starters",
    title: "How Php Works?",
    content:
      "The PHP software works with the The PHP software works with the  The PHP software works with the  The PHP software works with the ",
    like: 55,
    comments: 22,
    author: "Shubh Jani",
    date: "2020-11-15",
    share: 15,
  },
  {
    id: 6,
    cat: "java",
    thumb: "https://source.unsplash.com/750x600/?food,starters",
    title: "How Php Works?",
    content:
      "The PHP software works with the The PHP software works with the  The PHP software works with the  The PHP software works with the ",
    like: 55,
    comments: 22,
    author: "Aachal Panchal",
    date: "2020-11-15",
    share: 15,
  },
  {
    id: 7,
    cat: "java",
    thumb: "https://source.unsplash.com/750x600/?food,starters",
    title: "How Php Works?",
    content:
      "The PHP software works with the The PHP software works with the  The PHP software works with the  The PHP software works with the ",
    like: 55,
    comments: 22,
    author: "Parth Maru",
    date: "2020-11-15",
    share: 15,
  },
  {
    id: 8,
    cat: "java",
    thumb: "https://source.unsplash.com/750x600/?food,starters",
    title: "How Php Works?",
    content:
      "The PHP software works with the The PHP software works with the  The PHP software works with the  The PHP software works with the ",
    like: 55,
    comments: 22,
    author: "vishw kadu",
    date: "2020-11-15",
    share: 15,
  },
  {
    id: 9,
    cat: "iOt",
    thumb: "https://source.unsplash.com/750x600/?food,starters",
    title: "How Php Works?",
    content:
      "The PHP software works with the The PHP software works with the  The PHP software works with the  The PHP software works with the ",
    like: 55,
    comments: 22,
    author: "Shubh Jani",
    date: "2020-11-15",
    share: 15,
  },
  {
    id: 10,
    cat: "iOt",
    thumb: "https://source.unsplash.com/750x600/?food,starters",
    title: "How Php Works?",
    content:
      "The PHP software works with the The PHP software works with the  The PHP software works with the  The PHP software works with the ",
    like: 55,
    comments: 22,
    author: "Aachal Panchal",
    date: "2020-11-15",
    share: 15,
  },
  {
    id: 11,
    cat: "React",
    thumb: "https://source.unsplash.com/750x600/?food,starters",
    title: "How Php Works?",
    content:
      "The PHP software works with the The PHP software works with the  The PHP software works with the  The PHP software works with the ",
    like: 55,
    comments: 22,
    author: "Parth Maru",
    date: "2020-11-15",
    share: 15,
  },
  {
    id: 12,
    cat: "React",
    thumb: "https://source.unsplash.com/750x600/?food,starters",
    title: "How Php Works?",
    content:
      "The PHP software works with the The PHP software works with the  The PHP software works with the  The PHP software works with the ",
    like: 55,
    comments: 22,
    author: "vishw kadu",
    date: "2020-11-15",
    share: 15,
  },
  {
    id: 13,
    cat: "React",
    thumb: "https://source.unsplash.com/750x600/?food,starters",
    title: "How Php Works?",
    content:
      "The PHP software works with the The PHP software works with the  The PHP software works with the  The PHP software works with the ",
    like: 55,
    comments: 22,
    author: "Shubh Jani",
    date: "2020-11-15",
    share: 15,
  },
  {
    id: 14,
    cat: "React",
    thumb: "https://source.unsplash.com/750x600/?food,starters",
    title: "How Php Works?",
    content:
      "The PHP software works with the The PHP software works with the  The PHP software works with the  The PHP software works with the ",
    like: 55,
    comments: 22,
    author: "Parth Maru",
    date: "2020-11-15",
    share: 15,
  },
  {
    id: 15,
    cat: "React",
    thumb: "https://source.unsplash.com/750x600/?food,starters",
    title: "How Php Works?",
    content:
      "The PHP software works with the The PHP software works with the  The PHP software works with the  The PHP software works with the ",
    like: 55,
    comments: 22,
    author: "vishw kadu",
    date: "2020-11-15",
    share: 15,
  },
  {
    id: 16,
    cat: "Python",
    thumb: "https://source.unsplash.com/750x600/?food,starters",
    title: "How Php Works?",
    content:
      "The PHP software works with the The PHP software works with the  The PHP software works with the  The PHP software works with the ",
    like: 55,
    comments: 22,
    author: "Aachal Panchal",
    date: "2020-11-15",
    share: 15,
  },
  {
    id: 17,
    cat: "Python",
    thumb: "https://source.unsplash.com/750x600/?food,starters",
    title: "How Php Works?",
    content:
      "The PHP software works with the The PHP software works with the  The PHP software works with the  The PHP software works with the ",
    like: 55,
    comments: 22,
    author: "Parth Maru",
    date: "2020-11-15",
    share: 15,
  },
  {
    id: 18,
    cat: "Python",
    thumb: "https://source.unsplash.com/750x600/?food,starters",
    title: "How Php Works?",
    content:
      "The PHP software works with the The PHP software works with the  The PHP software works with the  The PHP software works with the ",
    like: 55,
    comments: 22,
    author: "vishw kadu",
    date: "2020-11-15",
    share: 15,
  },
  {
    id: 18,
    cat: "C",
    thumb: "https://source.unsplash.com/750x600/?food,starters",
    title: "How Php Works?",
    content:
      "The PHP software works with the The PHP software works with the  The PHP software works with the  The PHP software works with the ",
    like: 55,
    comments: 22,
    author: "Shubh Jani",
    date: "2020-11-15",
    share: 15,
  },
  {
    id: 18,
    cat: "C",
    thumb: "https://source.unsplash.com/750x600/?food,starters",
    title: "How Php Works?",
    content:
      "The PHP software works with the The PHP software works with the  The PHP software works with the  The PHP software works with the ",
    like: 55,
    comments: 22,
    author: "Aachal Panchal",
    date: "2020-11-15",
    share: 15,
  },
  {
    id: 18,
    cat: "C",
    thumb: "https://source.unsplash.com/750x600/?food,starters",
    title: "How Php Works?",
    content:
      "The PHP software works with the The PHP software works with the  The PHP software works with the  The PHP software works with the ",
    like: 55,
    comments: 22,
    author: "Parth Maru",
    date: "2020-11-15",
    share: 15,
  },
  {
    id: 18,
    cat: "Cpp",
    thumb: "https://source.unsplash.com/750x600/?food,starters",
    title: "How Php Works?",
    content:
      "The PHP software works with the The PHP software works with the  The PHP software works with the  The PHP software works with the ",
    like: 55,
    comments: 22,
    author: "Shubh Jani",
    date: "2020-11-15",
    share: 15,
  },
  {
    id: 18,
    cat: "Cpp",
    thumb: "https://source.unsplash.com/750x600/?food,starters",
    title: "How Php Works?",
    content:
      "The PHP software works with the The PHP software works with the  The PHP software works with the  The PHP software works with the ",
    like: 55,
    comments: 22,
    author: "vishw kadu",
    date: "2020-11-15",
    share: 15,
  },
  {
    id: 20,
    cat: "DBMS",
    thumb: "https://source.unsplash.com/750x600/?food,starters",
    title: "How Php Works?",
    content:
      "The PHP software works with the The PHP software works with the  The PHP software works with the  The PHP software works with the ",
    like: 55,
    comments: 22,
    author: "Parth Maru",
    date: "2020-11-15",
    share: 15,
  },
];
